apiVersion: v1
kind: Service
metadata:
  # internal services should be named after what the other application is looking for...
  # we know that the worker will look for a host named db
  # so we name the service db
  name: db
  labels:
    name: db-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432 # source port
      targetPort: 5432
  # link to a particular pod
  selector:
    # link this service to the postgres pod, using the labels defined on the postgres pod definition
    name: postgres-pod
    app: demo-voting-app