apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
#    labels here are not essential, because this service is not queried by other resources on the cluster
    name: result-service
    app: demo-voting-app
spec:
  # change the default type for this service (ClusterIP), so it is accesible from outside of the cluster
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 80 # source port
      targetPort: 80
  # link to a particular pod
  selector:
    # link this service to the redis pod, using the labels defined on the redis pod definition
    name: result-app-pod
    app: demo-voting-app