apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  # change the default type for this service (ClusterIP), so it is accesible from outside of the cluster
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 80 # source port
      targetPort: 80
  # link to a particular pod
  selector:
    # link this service to the redis pod, using the labels defined on the redis pod definition
    name: voting-app-pod
    app: demo-voting-app